package com.example.parasdhanta.stressmanagement.fragments;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;

import com.example.parasdhanta.stressmanagement.R;
import com.example.parasdhanta.stressmanagement.dialogs.DialogConstants;
import com.example.parasdhanta.stressmanagement.dialogs.mCustomDialog;
import com.example.parasdhanta.stressmanagement.managers.BaseFragment;
import com.example.parasdhanta.stressmanagement.pojos.eventbus.FragmentArguements;

import org.greenrobot.eventbus.EventBus;
import org.greenrobot.eventbus.Subscribe;
import org.greenrobot.eventbus.ThreadMode;

import butterknife.BindView;
import butterknife.OnClick;

/**
 * Created by Paras Dhanta on 10/27/2016.
 */

public class DescriptionFragment extends BaseFragment {

    Toolbar mToolbar;

    private String fragTitle,fragContentDescrtiption;
    View rootView;

    @BindView(R.id.what_is_text)
    TextView whatIsConditionTxt;

    @BindView(R.id.symptoms_of_text)
    TextView symptomTxt;

    @BindView(R.id.viewmore_about)
    Button viewMoreAboutBut;

    @BindView(R.id.viewmore_causes)
    Button viewMoreCausesBut;

    @BindView(R.id.viewmore_symptoms)
    Button viewMoreSympsBut;

    @BindView(R.id.cause_of_text)
    TextView causeOfTxt;

    @Nullable
    @OnClick({R.id.viewmore_about,R.id.viewmore_causes,R.id.viewmore_symptoms})
    public void onFragmentButtonCLick(View view){
        if(view.getId()==R.id.viewmore_about){
              startDialogFragment("What is "+whatIsConditionTxt.getText().toString());
        }
        else if(view.getId()==R.id.viewmore_causes){
            startDialogFragment("Causes of "+causeOfTxt.getText().toString());
        }
        else{
            startDialogFragment("Symptoms of "+symptomTxt.getText().toString());

        }
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setHasOptionsMenu(true);
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        super.onCreateView(inflater, container, savedInstanceState);
        // Inflate the layout resource that'll be returned
        rootView = inflater.inflate(R.layout.condition_desc_fragment, container, false);

        super.initButterKnife(rootView);

        return rootView;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
    }

    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        super.onCreateOptionsMenu(menu, inflater);
    }

    @Override
    public void onResume() {
        super.onResume();
        //set toolbar on fragment
        setToolbar();

        // set text on the condition textviews
        setTextOnTextViews();
    }

    public String getFragTitle() {
        return fragTitle;
    }

    public void setFragTitle(String fragTitle) {
        this.fragTitle = fragTitle;
    }

    /*Sticky event listener for events generated by activity*/
    @Subscribe(sticky = true,threadMode = ThreadMode.MAIN)
    public void getFragmentParams(FragmentArguements fragmentArguements) {
        setFragTitle(fragmentArguements.getTitle());
        this.fragContentDescrtiption = fragmentArguements.getContent();
    }

    @Override
    public void onStop() {
        //un register the event bus object fro the current fragment when activity stops
        EventBus.getDefault().unregister(this);
        EventBus.getDefault().removeStickyEvent(this);
        super.onStop();
    }

    @Override
    public void onStart() {
        super.onStart();

        //resgister the event bus to listen for events from activity
        EventBus.getDefault().register(DescriptionFragment.this);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        return super.onOptionsItemSelected(item);

    }

    @Override
    public void onPause() {
        super.onPause();
    }

    public void setToolbar() {
        /**
         * Changes the icon of the drawer to menu
         */
            if (getActivity() instanceof AppCompatActivity) {
                mToolbar= (Toolbar) ((AppCompatActivity) getActivity()).findViewById(R.id.main_toolbar);
                mToolbar.setNavigationIcon(R.drawable.abc_ic_ab_back_material);
                mToolbar.setTitle(getFragTitle());
                mToolbar.setNavigationOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        getActivity().onBackPressed();
                    }
                });
            }
    }

    public void setTextOnTextViews(){
        whatIsConditionTxt.setText(getFragTitle().toLowerCase());
        causeOfTxt.setText(getFragTitle().toLowerCase());
        symptomTxt.setText(getFragTitle().toLowerCase());
    }

    public void startDialogFragment(String dialogHeading){

        Bundle bundle=new Bundle();
        bundle.putString(DialogConstants.DESCRIPTION_DIALOG_TITLE_KEY,dialogHeading);
        bundle.putString(DialogConstants.DESCRIPTION_DIALOG_CONTENT_KEY,getResources().getString(R.string.temp));

        mCustomDialog mDialog = new mCustomDialog();
        mDialog.setArguments(bundle);

        mDialog.getInstance((AppCompatActivity) getActivity(),R.layout.view_more_dialog);
        mDialog.show(getActivity().getFragmentManager(),"");

    }

}
